server:
#  port: 9191 被 clash 占用
  port: 9292

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        # 当线程池中的任务队列已满，并且没有空闲线程可以执行新任务时，CallerRunsPolicy 会将任务回退到调用者线程中运行。这种策略适用于不希望丢失任务且可以接受调用者线程被阻塞的场景。
        policy: CallerRunsPolicy
# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
# willchan-tech扳手通用组件配置
java-forge:
  # 限流配置
  rate-limiter:
    global:
      permits-per-second: 2
  # 日志脱敏配置
  log-mask:
    enabled: true
    phone: true
    email: true
    idCard: true
    passport: true
  dynamic-config:
    # 不同的项目，system 应该不同。
    system: test-system
    redis:
      # redis host
      host: 127.0.0.1
      # redis port
      port: 16379
  # 任务调度配置
  task-job:
      enabled: false # 是否开启定时刷新任务
      pool-size: 5 # 任务线程池大小
      thread-name-prefix: "test-task-scheduler-" # 任务线程名称前缀
      wait-for-tasks-to-complete-on-shutdown: true # 是否等待任务执行完成再关闭容器
      await-termination-seconds: 30 # 容器关闭时，等待任务执行完成，超时（n 秒）则强制中断
      refresh-interval: 30000 # 刷新任务间隔（ms）
#      clean-invalid-tasks-cron: "0 0/5 0/6 * * ?"