server:
#  port: 9191 被 clash 占用
  port: 9292

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        # 当线程池中的任务队列已满，并且没有空闲线程可以执行新任务时，CallerRunsPolicy 会将任务回退到调用者线程中运行。这种策略适用于不希望丢失任务且可以接受调用者线程被阻塞的场景。
        policy: CallerRunsPolicy
# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
# willchan-tech扳手通用组件配置
java-forge:
  # 限流配置
  rate-limiter:
    global:
      permits-per-second: 2
  # 日志脱敏配置
  log-mask:
    enabled: true
    phone: true
    email: true
    idCard: true
    passport: true
  dynamic-config:
    # 不同的项目，system 应该不同。
    system: test-system
    redis:
      # redis host
      host: 127.0.0.1
      # redis port
      port: 16379
  # 任务调度配置
  task-job:
      enabled: false
      pool-size: 5
      thread-name-prefix: "test-task-scheduler-"
      wait-for-tasks-to-complete-on-shutdown: true
      await-termination-seconds: 30
      refresh-interval: 30000
      clean-invalid-tasks-cron: "0 0/5 0/6 * * ?"